name: Sonos Player
slug: sonos_player
version: "0.1.19"
description: Headless Sonos group manager service for Home Assistant
url: https://github.com/eranknafo2001/sonos-player-ha
startup: services
boot: auto
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Sonos Player API
options:
  sonos_host: ""
  sonos_port: 1400
  sonos_discovery_timeout: 10
  mqtt_url: mqtt://core-mosquitto:1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_discovery_prefix: homeassistant
  api_port: 8099
  api_token: ""
schema:
  sonos_host: str?
  sonos_port: port
  sonos_discovery_timeout: int(1,120)
  mqtt_url: str
  mqtt_user: str?
  mqtt_password: password?
  mqtt_discovery_prefix: str?
  api_port: port
  api_token: password?
